##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  archlinux:
    # Useful URL: https://git.archlinux.org/svntogit/community.git/tree/mozo
    - gcc
    - git
    - gtk3
    - intltool
    - make
    - mate-common
    - mate-menus
    - python-gobject
    - which

  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/mozo
    - gettext
    - git
    - intltool
    - libmate-menu-dev
    - make
    - mate-common
    - python-gi-dev
    - python3

  fedora:
    # Useful URL: https://src.fedoraproject.org/cgit/rpms/mozo.git
    - desktop-file-utils
    - gcc
    - git
    - make
    - mate-common 
    - mate-menus-devel
    - pygobject3-devel
    - python3-devel
    - redhat-rpm-config

  ubuntu:
    - gettext
    - git
    - intltool
    - libmate-menu-dev
    - make
    - mate-common
    - python-gi-dev
    - python3

variables:
  - CFLAGS="-Wall -Werror=format-security"

before_scripts:
  - if [ ${DISTRO_NAME} == "debian" ];then
  -     curl -Ls -o debian.sh https://github.com/mate-desktop/mate-dev-scripts/raw/master/travis/debian.sh
  -     bash ./debian.sh
  - fi

after_scripts:
  - make distcheck

releases:
  draft: false
  prerelease: false
  checksum: true
  file_glob: true
  files: mozo-*.tar.xz
  github_release:
    tags: true
    overwrite: true
    base_version: 1.20.0
    notify_servers:
      - https://release.mate-desktop.org/release
